only_rules:
  - colon
  - fatal_error_message
  - implicitly_unwrapped_optional
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - operator_usage_whitespace
  - return_arrow_whitespace
  - trailing_newline
  - unused_optional_binding
  - vertical_whitespace
  - void_return
  - unowned_variable_capture
  - custom_rules

excluded:
  - vendor
  - DerivedData
  - Packages

# Don't fail if there are no files to lint, useful when supplying direct files to lint (pre-commit hook and CI).
allow_zero_lintable_files: true

indentation: 4
